// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/google/wire"
	"github.com/sankangkin/di-rest-api/internal/database"
	"github.com/sankangkin/di-rest-api/internal/domain/category"
)

// Injectors from wire.go:

func InitCategory() (*category.CategoryHandler, error) {
	db, err := database.NewDB()
	if err != nil {
		return nil, err
	}
	categoryRepositoryInterface := category.NewCategoryRepository(db)
	categoryServiceInterface := category.NewCategoryService(categoryRepositoryInterface)
	categoryHandler := category.NewCategoryHandler(categoryServiceInterface)
	return categoryHandler, nil
}

// wire.go:

var CategoryWireSet = wire.NewSet(database.NewDB, category.NewCategoryRepository, category.NewCategoryService, category.NewCategoryHandler)
