// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/google/wire"
	"github.com/sankangkin/di-rest-api/internal/database"
	"github.com/sankangkin/di-rest-api/internal/domain/cashbook"
	"github.com/sankangkin/di-rest-api/internal/domain/sale"
)

// Injectors from wire.go:

func InitSaleDI() (*sale.SaleHandler, error) {
	db, err := database.NewDB()
	if err != nil {
		return nil, err
	}
	cashbookRepositoryInterface := cashbook.NewCashbookRepository(db)
	saleRepositoryInterface := sale.NewSaleRepository(db, cashbookRepositoryInterface)
	saleServiceInterface := sale.NewSaleService(saleRepositoryInterface, cashbookRepositoryInterface)
	saleHandler := sale.NewSaleHandler(saleServiceInterface)
	return saleHandler, nil
}

// wire.go:

var SaleWireSet = wire.NewSet(database.NewDB, cashbook.NewCashbookRepository, sale.NewSaleRepository, sale.NewSaleService, sale.NewSaleHandler)
