// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/google/wire"
	"github.com/sankangkin/di-rest-api/internal/database"
	"github.com/sankangkin/di-rest-api/internal/domain/productstock"
)

// Injectors from wire.go:

func InitProductStockDI() (*productstock.ProductStockHandler, error) {
	db, err := database.NewDB()
	if err != nil {
		return nil, err
	}
	productStockRepositoryInterface := productstock.NewProductStockRepository(db)
	productStockHandler := productstock.NewProductStockHandler(productStockRepositoryInterface)
	return productStockHandler, nil
}

// wire.go:

var ProductStockWireSet = wire.NewSet(database.NewDB, productstock.NewProductStockRepository, productstock.NewProductStockService, productstock.NewProductStockHandler)
