// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/google/wire"
	"github.com/sankangkin/di-rest-api/internal/database"
	"github.com/sankangkin/di-rest-api/internal/domain/unitconversion"
)

// Injectors from wire.go:

func InitUnitConversionDI() (*unitconversion.UnitConversionHandler, error) {
	db, err := database.NewDB()
	if err != nil {
		return nil, err
	}
	unitConversionRepositoryInterface := unitconversion.NewUnitConversionRepository(db)
	unitConversionServiceInterface := unitconversion.NewUnitConversionService(unitConversionRepositoryInterface)
	unitConversionHandler := unitconversion.NewUnitConversionHandler(unitConversionServiceInterface)
	return unitConversionHandler, nil
}

// wire.go:

var UnitConversionWireSet = wire.NewSet(database.NewDB, unitconversion.NewUnitConversionRepository, unitconversion.NewUnitConversionService, unitconversion.NewUnitConversionHandler)
