// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/google/wire"
	"github.com/sankangkin/di-rest-api/internal/database"
	"github.com/sankangkin/di-rest-api/internal/domain/expense"
)

// Injectors from wire.go:

func InitExpense() (*expense.ExpenseHandler, error) {
	db, err := database.NewDB()
	if err != nil {
		return nil, err
	}
	expenseRepositoryInterface := expense.NewExpenseRepository(db)
	expenseServiceInterface := expense.NewExpenseService(expenseRepositoryInterface)
	expenseHandler := expense.NewExpenseHandler(expenseServiceInterface)
	return expenseHandler, nil
}

// wire.go:

var ExpenseWireSet = wire.NewSet(database.NewDB, expense.NewExpenseRepository, expense.NewExpenseService, expense.NewExpenseHandler)
