// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/google/wire"
	"github.com/sankangkin/di-rest-api/internal/database"
	"github.com/sankangkin/di-rest-api/internal/handler"
	"github.com/sankangkin/di-rest-api/internal/repository"
	"github.com/sankangkin/di-rest-api/internal/service"
)

// Injectors from wire.go:

func InitCategory() (*handler.CategoryHandler, error) {
	db, err := database.NewDB()
	if err != nil {
		return nil, err
	}
	categoryRepositoryInterface := repository.NewCategoryRepository(db)
	categoryServiceInterface := service.NewCategoryService(categoryRepositoryInterface)
	categoryHandler := handler.NewCategoryHandler(categoryServiceInterface)
	return categoryHandler, nil
}

// wire.go:

var CategoryWireSet = wire.NewSet(database.NewDB, repository.NewCategoryRepository, service.NewCategoryService, handler.NewCategoryHandler)
