// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/google/wire"
	"github.com/sankangkin/di-rest-api/internal/database"
	"github.com/sankangkin/di-rest-api/internal/domain/unitofmeasurement"
)

// Injectors from wire.go:

func InitUnitOfMeasurementDI() (*unitofmeasurement.UnitOfMeasurementHandler, error) {
	db, err := database.NewDB()
	if err != nil {
		return nil, err
	}
	unitOfMeasurementRepositoryInterface := unitofmeasurement.NewUnitOfMeasurementRepository(db)
	unitOfMeasurementServiceInterface := unitofmeasurement.NewUnitOfMeasurementService(unitOfMeasurementRepositoryInterface)
	unitOfMeasurementHandler := unitofmeasurement.NewUnitOfMeasurementHandler(unitOfMeasurementServiceInterface)
	return unitOfMeasurementHandler, nil
}

// wire.go:

var UnitOfMeasurementWireSet = wire.NewSet(database.NewDB, unitofmeasurement.NewUnitOfMeasurementRepository, unitofmeasurement.NewUnitOfMeasurementService, unitofmeasurement.NewUnitOfMeasurementHandler)
