// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/google/wire"
	"github.com/sankangkin/di-rest-api/internal/database"
	"github.com/sankangkin/di-rest-api/internal/domain/cashbook"
)

// Injectors from wire.go:

func InitCashbook() (*cashbook.CashbookHandler, error) {
	db, err := database.NewDB()
	if err != nil {
		return nil, err
	}
	cashbookRepositoryInterface := cashbook.NewCashbookRepository(db)
	cashbookServiceInterface := cashbook.NewCashbookService(cashbookRepositoryInterface, db)
	cashbookHandler := cashbook.NewCashbookHandler(cashbookServiceInterface)
	return cashbookHandler, nil
}

// wire.go:

var CashbookWireSet = wire.NewSet(database.NewDB, cashbook.NewCashbookRepository, cashbook.NewCashbookService, cashbook.NewCashbookHandler)
