// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/google/wire"
	"github.com/sankangkin/di-rest-api/internal/auth"
	"github.com/sankangkin/di-rest-api/internal/database"
)

// Injectors from wire.go:

func InitAuth() (*auth.AuthHandler, error) {
	db, err := database.NewDB()
	if err != nil {
		return nil, err
	}
	authRepositoryInterface := auth.NewAuthRepository(db)
	authServiceInterface := auth.NewAuthService(authRepositoryInterface)
	authHandler := auth.NewAuthHandler(authServiceInterface)
	return authHandler, nil
}

// wire.go:

var AuthWireSet = wire.NewSet(database.NewDB, auth.NewAuthRepository, auth.NewAuthService, auth.NewAuthHandler)
