// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/google/wire"
	"github.com/sankangkin/di-rest-api/internal/database"
	"github.com/sankangkin/di-rest-api/internal/domain/customer"
)

// Injectors from wire.go:

func InitCustomer() (*customer.CustomerHandler, error) {
	db, err := database.NewDB()
	if err != nil {
		return nil, err
	}
	customerRepositoryInterface := customer.NewCustomerRepository(db)
	customerServiceInterface := customer.NewCustomerService(customerRepositoryInterface)
	customerHandler := customer.NewCustomerHandler(customerServiceInterface)
	return customerHandler, nil
}

// wire.go:

var CustomerWireSet = wire.NewSet(database.NewDB, customer.NewCustomerRepository, customer.NewCustomerService, customer.NewCustomerHandler)
