// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/google/wire"
	"github.com/sankangkin/di-rest-api/internal/database"
	"github.com/sankangkin/di-rest-api/internal/domain/productprice"
)

// Injectors from wire.go:

func InitProductPriceDI() (*productprice.ProductPriceHandler, error) {
	db, err := database.NewDB()
	if err != nil {
		return nil, err
	}
	productPriceRepositoryInterface := productprice.NewProductPriceRepository(db)
	productPriceServiceInterface := productprice.NewProductPriceService(productPriceRepositoryInterface)
	productPriceHandler := productprice.NewProductPriceHandler(productPriceServiceInterface)
	return productPriceHandler, nil
}

// wire.go:

var ProductPriceWireSet = wire.NewSet(database.NewDB, productprice.NewProductPriceRepository, productprice.NewProductPriceService, productprice.NewProductPriceHandler)
