// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/google/wire"
	"github.com/sankangkin/di-rest-api/internal/database"
	"github.com/sankangkin/di-rest-api/internal/domain/cashbook"
	"github.com/sankangkin/di-rest-api/internal/domain/purchase"
)

// Injectors from wire.go:

func InitPurchaseDI() (*purchase.PurchaseHandler, error) {
	db, err := database.NewDB()
	if err != nil {
		return nil, err
	}
	cashbookRepositoryInterface := cashbook.NewCashbookRepository(db)
	purchaseRepositoryInterface := purchase.NewSaleRepository(db, cashbookRepositoryInterface)
	purchaseServiceInterface := purchase.NewSaleService(purchaseRepositoryInterface, cashbookRepositoryInterface)
	purchaseHandler := purchase.NewSaleHandler(purchaseServiceInterface)
	return purchaseHandler, nil
}

// wire.go:

var PurchaseWireSet = wire.NewSet(database.NewDB, cashbook.NewCashbookRepository, purchase.NewSaleRepository, purchase.NewSaleService, purchase.NewSaleHandler)
