// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/google/wire"
	"github.com/sankangkin/di-rest-api/internal/database"
	"github.com/sankangkin/di-rest-api/internal/domain/product"
)

// Injectors from wire.go:

func InitProductDI() (*product.ProductHandler, error) {
	db, err := database.NewDB()
	if err != nil {
		return nil, err
	}
	productRepositoryInterface := product.NewProductRepository(db)
	productHandler := product.NewProductHandler(productRepositoryInterface)
	return productHandler, nil
}

// wire.go:

var ProductWireSet = wire.NewSet(database.NewDB, product.NewProductRepository, product.NewProductService, product.NewProductHandler)
